defmodule EvoGit.Runtime.Genesis do
  @moduledoc "Stage 1: Creation Phase"
  alias EvoGit.Agent
  alias EvoGit.Core.PhyloGraphNode
  alias EvoGit.Adapters.Git
  require Logger

  def run(root_prompt) do
    Logger.info("Genesis: Starting with root prompt: #{root_prompt}")

    with :ok <- ensure_repo(),
         {:ok, head_sha} <- PhyloGraphNode.current_head() do
      # Start recursion from root "."
      evolve_node(head_sha, ".", root_prompt)
    else
      error ->
        Logger.error("Genesis failed to initialize: #{inspect(error)}")
        error
    end
  end

  defp ensure_repo do
    if File.dir?(".git") do
      :ok
    else
      Logger.info("Genesis: Initializing Git repository...")
      Git.init(".")
      # Create initial commit to allow branching
      File.write!("README.md", "# EvoGit Project\nGenerated by EvoGit Genesis.")
      Git.add(".", "README.md")

      case Git.commit(".", "Initial commit") do
        {:ok, _} -> :ok
        error -> error
      end
    end
  end

  # The Core Recursive Function
  defp evolve_node(current_sha, node_path, context_instruction) do
    Logger.info("Genesis: Evolving #{node_path} from #{String.slice(current_sha, 0, 7)}")

    # Step 2: Plan
    # Create/Update CONTEXT.md (or file header)
    plan_objective = """
    Planning Phase for #{node_path}.
    Instruction: #{context_instruction}
    Task:
    - If '#{node_path}' is a directory, create or update 'CONTEXT.md' inside it.
      Define Intent, API Surface, and Constraints.
    - If '#{node_path}' is a file, add a header comment defining its purpose.
    """

    with {:ok, plan_state} <-
           Agent.mutate(%{commit_sha: current_sha, node_path: node_path}, plan_objective),
         # Step 3: Realize
         # Create structure or implementation
         realize_objective = """
         Realization Phase for #{node_path}.
         Context is defined in CONTEXT.md (or header) of this node.
         Task:
         - If '#{node_path}' is a directory, create the immediate subdirectories and empty files specified in the context.
           Do NOT implement the content of the children files yet, just create them.
         - If '#{node_path}' is a file, implement the full code according to the header.
         """,
         {:ok, realize_state} <- Agent.mutate(plan_state, realize_objective) do
      # Step 4: Recursion
      # Find children created/present in realize_state.commit_sha
      recurse_children(realize_state.commit_sha, node_path)
    end
  end

  defp recurse_children(base_sha, node_path) do
    case PhyloGraphNode.list_immediate_children(base_sha, node_path) do
      {:ok, children} ->
        # Filter children
        valid_children =
          children
          |> Enum.reject(fn p ->
            # Remove artifacts and self
            name = Path.basename(p)
            name == ".git" or name == "CONTEXT.md" or p == node_path
          end)

        if valid_children == [] do
          {:ok, %{commit_sha: base_sha, node_path: node_path}}
        else
          Logger.info(
            "Genesis: Recursing into children of #{node_path}: #{inspect(valid_children)}"
          )

          process_children_parallel(base_sha, valid_children)
        end

      error ->
        error
    end
  end

  defp process_children_parallel(base_sha, children) do
    # Use Task.async_stream for parallel agents
    # Manage resources by limiting concurrency to typical pool size (3)
    results =
      Task.async_stream(
        children,
        fn child_path ->
          evolve_node(base_sha, child_path, "Inherit context from parent")
        end,
        timeout: :infinity,
        max_concurrency: 3
      )

    # Collect results and merge them sequentially into the base
    # Note: Each child returns a state with a commit that is (base + child_changes)
    # We need to merge them all together.
    Enum.reduce_while(results, base_sha, fn
      {:ok, {:ok, %{commit_sha: child_sha}}}, current_base ->
        Logger.info(
          "Genesis: Merging child #{String.slice(child_sha, 0, 7)} into #{String.slice(current_base, 0, 7)}"
        )

        case merge_branch(current_base, child_sha) do
          {:ok, new_base} -> {:cont, new_base}
          error -> {:halt, error}
        end

      {:ok, {:error, reason}}, _ ->
        {:halt, {:error, reason}}

      {:exit, reason}, _ ->
        {:halt, {:error, reason}}
    end)
    |> case do
      {:error, _} = err -> err
      sha when is_binary(sha) -> {:ok, %{commit_sha: sha, node_path: "."}}
    end
  end

  defp merge_branch(base_sha, other_sha) do
    # Use Agent.resolve_conflict to handle the merge (and potential conflicts)
    # It manages the worktree resource via WorkerPool
    state = %{commit_sha: base_sha, node_path: "."}

    case Agent.resolve_conflict(state, other_sha) do
      {:ok, %{commit_sha: new_sha}} -> {:ok, new_sha}
      error -> error
    end
  end
end
