defmodule EvoGit.Agent.Tools.SpawnInvestigator do
  @moduledoc """
  Placeholder tool for spawning an investigator subagent.

  v1: the schema is IDENTICAL to the real `subagent_investigator` subagent
  tool (see `EvoGit.Agent.SubagentSchemas.schemas/1` +
  `EvoGit.Agents.Investigator`), but `execute/3` does NOT spawn anything — it
  explains that investigator subagent spawning ships with the bundled Genesis
  source (LSP-style) in a future release and points the agent at its own
  read-only investigation tools.
  """

  alias EvoGit.Agent.Tools.Shared

  @doc """
  Returns the tool schema for ReqLLM.

  Copied verbatim from the `subagent_investigator` schema generated by
  `EvoGit.Agent.SubagentSchemas.schemas/1` so a real implementation can slot
  in later without schema changes.
  """
  def schema do
    ReqLLM.tool(
      name: "subagent_investigator",
      description:
        "[Subagent] A specialized agent for codebase analysis. Call this subagent with a query " <>
          "to let it investigate the codebase and return a report. " <>
          "The investigator has read-only access and can also update directory CONTEXT.md files. " <>
          "Use this to understand code structure, find patterns, trace dependencies, or investigate test results — " <>
          "especially when you need information from a child directory before deciding how to proceed.",
      parameter_schema: %{
        "type" => "object",
        "properties" => %{
          "path" => %{
            "type" => "string",
            "description" =>
              "The path to a DIRECTORY where the subagent should operate. " <>
                "Use a RELATIVE path from the repository root for the current project (e.g., './src/auth', './lib/utils'). " <>
                "Use an ABSOLUTE path to delegate to a FOREIGN REPOSITORY configured in genesis.toml " <>
                "(e.g., '/Source/original-proj'). MUST be a directory node, NOT a file path.\n\n" <>
                "IMPORTANT: Delegate at the DEEPEST correct node you know — if your routing table shows work belongs in `./src/auth/oauth/`, " <>
                "delegate there directly, not at the higher-level `./src/auth/`. The subagent has its own routing table and will navigate further.\n\n" <>
                "IMPORTANT: When delegating to a foreign repo, prefer using the repository ROOT path " <>
                "(e.g., '/Source/original-proj' rather than '/Source/original-proj/src'). " <>
                "Since you have no prior knowledge of the foreign repo's structure, starting at the root " <>
                "allows the subagent to discover the codebase layout via its CONTEXT.md routing table. " <>
                "Spawning at a non-root path is allowed but discouraged unless you have specific knowledge of that path.\n\n" <>
                "IMPORTANT: Delegating work to child directories is more efficient than editing files there yourself. " <>
                "When you find yourself repeatedly editing files in the same child directory, spawn a subagent at that path to handle the work autonomously."
          },
          "objective" => %{
            "type" => "string",
            "description" =>
              "A clear, self-contained objective for the subagent. " <>
                "Include any relevant context since it starts with a fresh context. " <>
                "IMPORTANT: The subagent's working directory is automatically set correctly. " <>
                "Do NOT include worktree paths or `cd` commands in the objective — just describe what to do (e.g., 'run `mix test`'). " <>
                "Include all relevant context, findings, and file paths so the subagent can start working immediately without re-investigating."
          },
          "commit_id" => %{
            "type" => "string",
            "description" =>
              "Optional: The commit SHA to spawn the subagent on. " <>
                "Defaults to HEAD if not specified or if set to an empty string."
          }
        },
        "required" => ["path", "objective"]
      },
      callback: fn _ -> {:ok, nil} end
    )
  end

  @doc """
  Executes the subagent_investigator tool (placeholder).

  Does NOT spawn anything. Validates the required `path`/`objective` args
  minimally (returning a descriptive error string when missing) and otherwise
  returns a message explaining that investigator subagent spawning ships with
  the bundled Genesis source in a future release, and that the agent should
  use its own read-only tools to investigate the Genesis source directly.
  """
  def execute(args, _repo_path, _repo_root) do
    with {:ok, _path} <- Shared.fetch_string_arg(args, "path"),
         {:ok, _objective} <- Shared.fetch_string_arg(args, "objective") do
      placeholder_message()
    end
  end

  defp placeholder_message do
    "Investigator subagent spawning is not available in this release — it ships " <>
      "with the bundled Genesis source (LSP-style) in a future release. " <>
      "Use your own read-only investigation tools instead — read_file, read_context, " <>
      "rg, glob, search_context, and search_history — to investigate the Genesis " <>
      "source directly (your repo_path points at the Genesis source root)."
  end
end
