defmodule EvoGit.Runtime.PullRequest do
  @moduledoc """
  Shared PR creation utilities used by both Genesis and Evolution phases.

  Provides LLM-powered PR title generation, PR body formatting,
  and the full push+PR creation flow.
  """

  alias EvoGit.Adapters.Git
  require Logger

  @doc """
  Attempts to create a GitHub pull request.

  Returns the PR URL on success, `nil` otherwise.
  Never raises — all failures are logged and return `nil`.
  """
  @spec try_create(String.t(), String.t(), String.t(), String.t()) :: {String.t(), String.t()} | {nil, nil}
  def try_create(repo_path, head_branch, objective, agent_result) do
    if Git.gh_available?() do
      with true <-
             Git.has_origin_remote?(repo_path) or
               create_remote_repo_and_continue(repo_path),
           {:ok, _current_branch} <- Git.current_branch(repo_path) do
        base_branch =
          case Git.origin_default_branch(repo_path) do
            {:ok, origin_default} -> origin_default
          end

        github_username = EvoGit.Config.resolve([:user, :github_username])
        pr_title = build_title(head_branch, objective, agent_result)
        pr_body = format_body(github_username, agent_result)

        # Ensure the base branch exists on the remote (e.g. for freshly created repos
        # where main was only initialized locally and never pushed).
        case Git.push_branch(repo_path, base_branch) do
          {:ok, _} ->
            Logger.info("Pushed base branch '#{base_branch}' to remote")

          {:error, {:conflict, output}} ->
            Logger.debug("Conflict pushing base branch '#{base_branch}': #{output}")

          {:error, {_code, output}} ->
            # Base branch may already exist on remote — log but don't abort
            Logger.debug("Could not push base branch '#{base_branch}': #{output}")
        end

        case Git.push_branch(repo_path, head_branch) do
          {:ok, _} ->
            Logger.info("Pushed branch '#{head_branch}' to remote")

            case Git.create_pull_request(repo_path, head_branch, base_branch, pr_title, pr_body) do
              {:ok, pr_url} ->
                Logger.info("Created pull request: #{pr_url}")
                {pr_url, pr_title}

              {:error, {_code, output}} ->
                Logger.warning("Failed to create pull request: #{output}")
                {nil, nil}
            end

          {:error, {:conflict, output}} ->
            Logger.warning("Conflict pushing branch '#{head_branch}': #{output}")
            {nil, nil}

          {:error, {_code, output}} ->
            Logger.warning("Failed to push branch '#{head_branch}': #{output}")
            {nil, nil}
        end
      else
        {:error, {_code, output}} ->
          Logger.warning("Failed to create remote repository: #{output}")
          {nil, nil}

        _ ->
          Logger.warning("Failed to set up remote repository")
          {nil, nil}
      end
    else
      Logger.info("'gh' CLI not available, skipping PR creation")
      {nil, nil}
    end
  end

  @doc """
  Generates a PR title by asking the LLM to summarize the objective and result.

  Falls back to the head branch name if no LLM model is configured or if
  the LLM call fails for any reason.
  """
  @spec generate_title(String.t(), String.t()) :: String.t() | nil
  def generate_title(objective, agent_result) do
    model = EvoGit.Config.resolve([:llm, :model])

    if is_nil(model) or model == "" do
      Logger.debug("No LLM model configured, skipping PR title generation")
      nil
    else
      generate_title_with_llm(model, objective, agent_result)
    end
  end

  @doc """
  Formats the PR body with a standard header and the agent's result.
  """
  @spec format_body(String.t(), String.t()) :: String.t()
  def format_body(github_username, agent_result) do
    """
    ## 🤖 Auto-generated by Genesis

    This pull request was automatically created by **Genesis** for @#{github_username}.

    ---

    ## Agent Result

    #{agent_result}
    """
  end

  # ---------------------------------------------------------------------------
  # Private helpers
  # ---------------------------------------------------------------------------

  defp build_title(head_branch, objective, agent_result) do
    case generate_title(objective, agent_result) do
      nil -> "Genesis: #{head_branch}"
      generated when is_binary(generated) and generated != "" -> "Genesis: #{generated}"
      _ -> "Genesis: #{head_branch}"
    end
  end

  defp generate_title_with_llm(model, objective, agent_result) do
    prompt = """
    Generate a short, meaningful PR title (max 8 words) from this objective and result.
    Output ONLY the title text, nothing else.

    Objective: #{objective}

    Result: #{String.slice(agent_result, 0, 2000)}
    """

    # We keep a rescue here (not just the `with` chain) because:
    # 1. ReqLLM.Context.new/1 and other setup calls can raise on unexpected input.
    # 2. The caller `try_create/4` has a "never raises" contract — all failures must
    #    return nil, which `build_title/3` handles by falling back to the branch name.
    # The `with` chain above handles {:error, _} tuples from ReqLLM functions;
    # this rescue is the last-resort guard for unexpected exceptions.
    try do
      context = ReqLLM.Context.new([ReqLLM.Context.user(prompt)])

      with {:ok, stream_response} <-
             ReqLLM.stream_text(model, context, provider_options: EvoGit.Config.Schema.LLM.provider_options_for_model(model)),
           {:ok, response} <- ReqLLM.StreamResponse.process_stream(stream_response),
           text <- ReqLLM.Response.text(response) do
        trimmed = String.trim(text)

        if trimmed == "" do
          Logger.warning("LLM returned empty title, falling back to branch name")
          nil
        else
          Logger.debug("Generated PR title via LLM: #{trimmed}")
          trimmed
        end
      else
        {:error, reason} ->
          Logger.warning("LLM title generation failed: #{inspect(reason)}")
          nil

        _ ->
          Logger.warning("LLM title generation failed with unexpected result")
          nil
      end
    rescue
      e ->
        Logger.warning("LLM title generation raised: #{Exception.message(e)}")
        nil
    end
  end

  defp create_remote_repo_and_continue(repo_path) do
    Logger.info("No origin remote found, creating remote repository...")

    case Git.create_origin_remote(repo_path) do
      {:ok, repo_url} ->
        Logger.info("Created remote repository: #{repo_url}")
        true

      {:error, {_code, output}} ->
        Logger.warning("Failed to create remote repository: #{output}")
        false
    end
  end
end
