import Config

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :evo_dash, EvoDashWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: String.to_integer(System.get_env("PORT") || "4100")],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "3glK92vjZ3r9mNf5sXT+ETZN7bEubviBPafm/ZkrbQWiRGbM9Vh1mWEvQUsx1xb6",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:evo_dash, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:evo_dash, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
# NOTE (Windows): live_reload's file watcher (file_system's inotifywait.exe,
# a .NET FileSystemWatcher with a fixed 8KB buffer) crashes with
# InternalBufferOverflowException under heavy _build/ asset churn and takes
# the whole dev server down. Keep patterns empty on Windows; browser refresh
# becomes manual, but code_reloader + esbuild/tailwind watchers still work.
live_reload_patterns =
  if :os.type() == {:win32, :nt},
    do: [],
    else: [
      ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"lib/evo_dash_web/(?:controllers|live|components|router)/?.*\.(ex|heex)$"
    ]

config :evo_dash, EvoDashWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: live_reload_patterns
  ]

# Same Windows issue: phoenix_live_reload's FileSystem monitor always starts
# and watches :dirs recursively (default [""] = the whole umbrella root,
# including _build/ and deps/, which overflows the watcher buffer). Restrict
# it to the small static-assets dir so it survives on Windows.
if :os.type() == {:win32, :nt} do
  config :phoenix_live_reload, :dirs, ["apps/evo_dash/priv/static"]
end

# Enable dev routes for dashboard and mailbox
config :evo_dash, dev_routes: true

# Do not include metadata or timestamps in development logs to keep output clean
config :logger, :default_formatter, format: "[$level] $message\n"

# SASL/OTP supervisor progress reports are disabled to reduce noise.
# Set handle_otp_reports: true, handle_sasl_reports: true to re-enable.

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application.

# Import local configuration if it exists, which is ignored by git
if File.exists?(Path.join(__DIR__, "dev.local.exs")) do
  import_config "dev.local.exs"
end
